### ISSUE TITLE
Resolution problems in installUtility at build time get missed in docker/podman build

### ISSUE THREAD

**Issue by bhasterix** [OpenLiberty/ci.docker#302] opened 2022-02-17 17:03 UTC
If the installUtility lines of configure.sh fail:
```
installUtility install --acceptLicense defaultServer --from=/tmp/repo.zip || if [ $? -ne 22 ]; then exit $?; fi
installUtility install --acceptLicense defaultServer || if [ $? -ne 22 ]; then exit $?; fi
```

Then they OR to logic to return the return code. This is flawed as tje second ‘$?’ will return 0 because the […] block did its job.
We need those lines updated to be:
```
installUtility install --acceptLicense defaultServer --from=/tmp/repo.zip || rc=$?; if [ $rc -ne 22 ]; then exit $rc; fi
installUtility install --acceptLicense defaultServer || rc=$?; if [ $rc -ne 22 ]; then exit $rc; fi
```
or something similar to allow the build to fail correctly in that case.

This has caused some erratic behavior with images we've built because certain dependencies of the applications were not met at build time.

**Comment by leochr** [comment] 2022-02-17 20:44
Closing as duplicate of https://github.com/WASdev/ci.docker/issues/431

**Closed by leochr** 2022-02-17 20:44 UTC
