### ISSUE TITLE
Question: Change server name from defaultServer

### ISSUE THREAD

**Issue by lancechant** [OpenLiberty/ci.docker#468] opened 2023-10-12 10:01 UTC
Hi

We are using the docker images, but one thing I can't change is the server name from defaultServer? as for logging when running multiple images of different applications they are all showing as defaultServer. It shows the application name correctly as it runs that

This is the current way we create an image 
`FROM open-liberty:23.0.0.6-kernel-slim-java11-openj9
ENV KEYSTORE_REQUIRED=false VERBOSE=true
EXPOSE 8080 8543
COPY --chown=1001 dependencies /opt/ol/wlp/usr/
COPY --chown=1001 config /config/ #this has the server.xml and a folder called apps, which as the war file
COPY --chown=1001 keystore /var/keystore/
RUN features.sh
RUN configure.sh`

Am I doing it correctly? I can provide more information if needed

**Comment by leochr** [comment] 2023-10-12 20:00
@lancechant The default server name has many references within the Liberty images (symlinks, startup process, permission settings, server cache, etc) and it's not customizable at the moment. But it's in our roadmap to support. We don't have a timeline to share at this time. Related issue: https://github.com/OpenLiberty/ci.docker/issues/284

**Comment by leochr** [comment] 2023-10-12 20:00
Closing as duplicate of https://github.com/OpenLiberty/ci.docker/issues/284

**Closed by leochr** 2023-10-12 20:00 UTC

**Comment by lancechant** [comment] 2023-10-13 05:33
Ah I see thanks, seemed to have missed that issue
